spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/apimlv2
    username: postgres
    password: postgres
  jackson:
    mapper:
      accept-case-insensitive-enums: true
jwt:
  secret: jdk02kdadnjndiawd
  expTime: 86400